apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: todoapp-cronjob
        spec:
          containers:
          - name: todoapp-cronjob
          image: busyboxplus:curl
          command: ["sh", "-c", "curl http://todoapp-service.mateapp.svc.cluster.local/api/health"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          restartPolicy: OnFailure
