apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  namespace: mateapp
  labels:
    app: busybox-daemonset
spec:
  selector:
    matchLabels:
      app: busybox-daemonset
  template:
    metadata:
      labels:
        app: busybox-daemonset
    spec:
      containers:
        - name: busybox-daemonset
          image: busyboxplus:curl
          command: ["sh", "-c", "curl http://todoapp-service.mateapp.svc.cluster.local && sleep 5"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 8081
              hostPort: 30008